<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$magewireViewModel = $block->getData('view_model');
$magewireUtility = $magewireViewModel->utils()->magewire();
?>
<?php if ($magewireUtility->canRequireMagewireJsLibrary()): ?>
    <div
        id="magewire-runtime-config"
        hidden
        x-data="magewireScript"
        x-bind="magewireScriptBindings"
    ></div>
<?php endif ?>
