<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\MagewireHyvaTheme\Magewire\Playwright\ScriptBootstrap\Counter;

/** @var Template $block */
/** @var Counter $magewire */
?>
<div id="script-bootstrap-counter">
    <span id="script-bootstrap-count"><?= (int) $magewire->count ?></span>
    <button id="script-bootstrap-increment" type="button" wire:click="increment">
        Increment
    </button>
</div>
